 export const Product = [
    {
        id: 1,
        image: "/clothe/longleg.png",
        name: "stunning strip",
        qty: 1,
        price: 200,
        category: 'women',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },

    {
        id: 2,
        image: "/clothe/alex.png",
        name: "women dress",
        qty: 1,
        price: 200,
        category: 'women',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 3,
        image: "/clothe/chalo.png",
        name: "women dress",
        qty: 1,
        price: 200,
        category: 'women',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 4,
        image: "/clothe/dom.png",
        name: "Beautiful dress",
        qty: 1,
        price: 200,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 5,
        image: "/clothe/man.png",
        name: "women n",
        qty: 1,
        price: 200,
        category: 'men',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 6,
        image: "/clothe/manny.png",
        name: "women dress",
        qty: 1,
        price: 200,
        category: 'men',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 7,
        image: "/clothe/pinkie.png",
        name: "Pink gown",
        qty: 1,
        price: 200,
        category: 'women',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 8,
        image: "/clothe/polo.png",
        name: "women dress",
        qty: 1,
        price: 200,
        category: 'unisex',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
    {
        id: 9,
        image: "/clothe/tamara.png",
        name: "women dress",
        qty: 1,
        price: 200,
        category: 'women',
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mauris enim, vestibulum sed nulla vel, tempor viverra leo. Cras eros libero, vestibulum at erat sit amet, bibendum ornare dolor.",
    },
];

export default Product;

